spring:
  application:
    name: ddd-sample

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

client:
  payment:
    base-url: http://localhost:9001
  inventory:
    base-url: http://localhost:9002
